config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  resources :searches
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :searches
  end
  # Defines the root path route ("/")
  root "searches#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/search.rb
class Search < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
  has_many :searches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  # GET /searches or /searches.json
  def index
    render
    # @searches = Search.all
  end

  # GET /searches/1 or /searches/1.json
  def show
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches or /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to search_url(@search), notice: "Search was successfully created." }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1 or /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to search_url(@search), notice: "Search was successfully updated." }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1 or /searches/1.json
  def destroy
    @search.destroy

    respond_to do |format|
      format.html { redirect_to searches_url, notice: "Search was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def search_params
      params.require(:search).permit(:search_query)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sengn</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/searches/_form.html.erb
<%= form_with(model: search) do |form| %>
  <% if search.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
        <% search.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :search_query, style: "display: block" %>
    <%= form.text_field :search_query %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/searches/_search.html.erb
<div id="<%= dom_id search %>">
  <p>
    <strong>Search query:</strong>
    <%= search.search_query %>
  </p>

</div>

app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= render "form", search: @search %>

<br>

<div>
  <%= link_to "Show this search", @search %> |
  <%= link_to "Back to searches", searches_path %>
</div>

app/views/searches/index.html.erb
<h1>Searches</h1>

app/views/searches/new.html.erb
<h1>New search</h1>

<%= render "form", search: @search %>

<br>

<div>
  <%= link_to "Back to searches", searches_path %>
</div>

app/views/searches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @search %>

<div>
  <%= link_to "Edit this search", edit_search_path(@search) %> |
  <%= link_to "Back to searches", searches_path %>

  <%= button_to "Destroy this search", @search, method: :delete %>
</div>

app/views/users/show.html.erb
<%= form_with(model: search) do |form| %>

    <% if search.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
        <% search.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :search_query, "Search something you would like to know:", class: "block mb-2" %>
  <div class="flex space-x-3">
    <%= form.text_field :search_query, class: "py-3 px-4 rounded border ring-0 focus:ring-4 focus:ring-orange-100 focus:shadow-none focus:border-orange-500 focus:outline-none" %>

    <%= form.submit 'Search', class: "px-4 py-3 font-medium
  bg-orange-300 text-neutal-900 rounded flex items-center cursor-pointer hover:bg-orange-400 focus:ring-4 ring-0 focus:ring-orange-100" %>
  </div>
<% end %>